language: node_js
node_js:
  - "14.17"

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ${SERVICE_PATH}/node_modules

  install:
    - npm install -g serverless
    - travis_retry npm install
    - cd ${SERVICE_PATH}
    - travis_retry npm install
    - cd -

  script:
    - cd ${SERVICE_PATH}
    - serverless deploy -s ${STAGE_NAME}
    - cd -

environments:
  - &SIT_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_SIT}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_SIT}

  - &PROD_ENV
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_PROD}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY_PROD}

jobs:
  include:
    # non-master branches deploys to stage named by the branch
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Notification API"
      if: type = push AND NOT branch = master
      env:
        - SERVICE_PATH="notification-api"
        - STAGE_NAME=sit
        - *SIT_ENV

    # master branch deploys to the 'prod' stage
    - <<: *DEPLOY_SERVICE_JOB
      name: "Deploy Notification API"
      if: type = push AND branch = master
      env:
        - SERVICE_PATH="notification-api"
        - STAGE_NAME=prod
        - *PROD_ENV